Socket controller refactoring2
Ai4n/library_socket_project pull request #7
Opened 2019-12-21 14:10 UTC by Ai4n

Please check it?

2019-12-23 15:39 UTC, dnlbl requested changes
needs work

2019-12-23 15:39 UTC, dnlbl commented on Server/src/main/Author.java
> +//	public Author (String name, String surname, Language language) {
delete unnecessary lines

2019-12-23 15:39 UTC, dnlbl commented on Server/src/main/ServerController.java
> -			if (request == null)
why removed if (request == null) continue;

2019-12-23 15:39 UTC, dnlbl commented on Server/src/main/ServerController.java
> +				addBookToUsersList(addBookToUsersBookListRequest.getBookId(),
change method's signature from "addBookToUsersList(String, String)" to "addBookToUsersBookListRequest(AddBookToUsersBookListRequest)"

2019-12-23 15:39 UTC, dnlbl commented on Server/src/socketExchange/IsLoginExistResponse.java
> +
add new line at the end of file

2019-12-23 15:39 UTC, dnlbl commented on ServerClient/src/main/AdminController.java
> +		System.out.println(userId);
remove System.out.println

2019-12-23 15:39 UTC, dnlbl commented on ServerClient/src/main/UserController.java
> +		} else if (!(user == null)) {
"else if" is unnecessary, use "if" instead
change !(user == null) to user != null

2019-12-23 15:39 UTC, dnlbl commented on ServerClient/src/main/UserController.java
> +			System.out.println(userId);
remove System.out.println

2019-12-23 15:39 UTC, dnlbl commented on ServerClient/src/socketExchange/GetAllUserBooksResponse.java
>  		public ArrayList<Book> getAllBooksList() {
incorrect format;
remove two tabulations, check format of all files

2019-12-23 15:39 UTC, dnlbl commented on Server/src/main/ServerController.java
> +		userRepo.deleteUserBook(userId, bookId);
why moved method to UserRepo class?

2019-12-23 15:39 UTC, dnlbl commented on ServerClient/src/main/SocketController.java
>  	public void write(String json) {
change method signature from write(String) to write(SocketExchange)

2019-12-23 15:39 UTC, dnlbl commented on ServerClient/src/main/SocketController.java
>  	public String readUtf() {
change method signature from readUtf(String) to read(SocketExchange)

2020-01-10 07:06 UTC, dnlbl requested changes
1 issue with "socket" package - models should not be in "controller" package 
correct structure:

socket:
-controller
-model:
--ServerMessage.java
--ServerExchange.java
--socket-exchange (All requests and responses here)

rework in both Server and Client projects

2020-01-10 08:57 UTC, Ai4n commented
Please check it

2020-01-11 08:20 UTC, Ai4n commented
Fixed

2020-01-11 09:12 UTC, dnlbl approved these changes

2020-01-11 09:13 UTC, merged