Module separation
Ai4n/library_socket_project pull request #9
Opened 2020-01-13 13:18 UTC by Ai4n

Add method closeSession();

2020-01-13 13:19 UTC, Ai4n commented
Hello! What's up? Check it please.

2020-01-14 03:50 UTC, dnlbl requested changes
can't properly check this pull request
you have to add "SocketExchange" and "Entities" modules to git
just add these folders to your project directory and make commit and push

2020-01-14 12:40 UTC, Ai4n commented
Check it please

2020-01-14 12:43 UTC, dnlbl approved these changes

2020-01-14 12:43 UTC, merged